:- include('./facts.pl').
:- include('./rule.pl').
:- include('./info.pl').
:- include('./jalankanUntav2.pl').
:- include('./investasi_rule.pl').
:- include('./pasangTrap.pl').
:- include('./endgame.pl').
:- include('./godshand.pl').
:- include('./turncontrol.pl').
